"use strict";
const $=id=>document.getElementById(id);let ref,plan={schema:1,name:'Lost Research Team',difficulty:'Ultimate',party:4,brief:'',waves:[],npcs:[]};
function option(el,value,text){const o=document.createElement('option');o.value=value;o.textContent=text;el.append(o)}
function text(el,value,cls){const p=document.createElement('p');p.textContent=value;if(cls)p.className=cls;el.append(p)}
function locationData(){const a=ref.floors.find(x=>x.area===Number($('area').value)),v=a.variants[Number($('variant').value)];return {episode:1,floor:Number($('floor').value),area:a.area,layout:v.layout,entities:v.entities,map:v.object_basename,table:v.table,room:$('room').value===''?null:Number($('room').value)}}
function rooms(){const a=ref.floors.find(x=>x.area===Number($('area').value)),v=a.variants[Number($('variant').value)];const g=ref.geometry.find(x=>x.map===v.setup_basename);$('room').replaceChildren();option($('room'),'','Choose a room');for(const id of g?.section_ids||[])option($('room'),id,'Room '+id);$('maplink').hidden=!g;if(g)$('maplink').href='https://github.com/DarkChas1DR/PSOBB-Quest-Database/blob/'+ref.revision+'/analysis/floor-database/geometry/'+g.map+'.png';$('location').textContent='Area '+a.area+' / '+v.object_basename+' / layout '+v.layout+' / entities '+v.entities+(g?'':' — geometry match unavailable');}
function area(){const a=ref.floors.find(x=>x.area===Number($('area').value));$('floor').value=a.default_floor;$('variant').replaceChildren();a.variants.forEach((v,i)=>option($('variant'),i,v.table+' · '+v.layout+'/'+v.entities));rooms();}
function store(){try{localStorage.setItem('psobb-plan-v1',JSON.stringify(plan))}catch{}}
function render(){for(const [key,target] of [['waves','waves'],['npcs','npcs']]){$(target).replaceChildren();plan[key].forEach((x,i)=>{const row=document.createElement('div');row.className='entry';text(row,(key==='waves'?'Wave '+x.wave+' · '+x.count+' × '+x.name:x.name+' · handler '+x.handler)+' · floor '+x.floor+' / area '+x.area+' / room '+x.room+' / '+x.map);const b=document.createElement('button');b.textContent='Remove';b.className='remove';b.onclick=()=>{plan[key].splice(i,1);render()};row.append(b);$(target).append(row)})}
$('review').replaceChildren();text($('review'),plan.waves.length+' wave entries · '+plan.waves.reduce((n,x)=>n+x.count,0)+' planned monster records · '+plan.npcs.length+' NPCs');if(!plan.waves.length)text($('review'),'Add at least one wave entry.','warning');if(plan.waves.length)text($('review'),'Enemy positions, event activation, door links and completion logic still need authoring.','warning');for(const x of [...plan.waves,...plan.npcs]){const d=ref.entities.find(d=>d.id===x.type);if(!d?.documented_areas.some(a=>a.episode===1&&a.area===x.area))text($('review'),x.name+': selected area compatibility is unverified.','warning')}
text($('review'),'Not ready for game export: compiler and client tests pending.','warning');store();}
function locValid(){const l=locationData();if(l.room===null||!Number.isInteger(l.floor)||l.floor<0||l.floor>255){alert('Choose a room and a floor slot between 0 and 255.');return null}return l}
$('area').onchange=area;$('variant').onchange=rooms;
$('add').onclick=()=>{const l=locValid();if(!l)return;const wave=Number($('wave').value),count=Number($('count').value);if(!Number.isInteger(wave)||wave<0||wave>65535||!Number.isSafeInteger(count)||count<1){alert('Use a wave ID from 0 to 65535 and a positive whole count. This checks encoding, not runtime capacity.');return}const d=ref.entities.find(x=>x.id===Number($('monster').value));plan.waves.push({...l,wave,count,type:d.id,name:d.qedit_name||d.constructor,positions:[],event:null});render()};
$('addnpc').onclick=()=>{const l=locValid();if(!l)return;const d=ref.entities.find(x=>x.id===Number($('npc').value));const position=['x','y','z'].map(k=>Number($(k).value)),handler=Number($('handler').value),facing=Number($('facing').value);if(!position.every(Number.isFinite)||!Number.isInteger(handler)||handler<0||!Number.isInteger(facing)){alert('Enter finite coordinates and whole handler/facing values.');return}plan.npcs.push({...l,type:d.id,name:d.qedit_name||d.constructor,position,coordinateSpace:'unverified',facing,handler,dialogue:$('dialogue').value,appearance:null});render()};
for(const k of ['name','difficulty','party','brief'])$(k).oninput=()=>{plan[k]=k==='party'?Number($(k).value):$(k).value;store()};
$('save').onclick=()=>{const b=new Blob([JSON.stringify({...plan,referenceRevision:ref.revision},null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='quest-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
function valid(p){return p&&p.schema===1&&typeof p.name==='string'&&typeof p.brief==='string'&&['Ultimate','Very Hard','Hard','Normal'].includes(p.difficulty)&&[1,2,3,4].includes(p.party)&&Array.isArray(p.waves)&&Array.isArray(p.npcs)&&[...p.waves,...p.npcs].every(x=>x&&typeof x.name==='string'&&Number.isInteger(x.type)&&Number.isInteger(x.room)&&Number.isInteger(x.floor)&&typeof x.map==='string')&&p.waves.every(x=>Number.isSafeInteger(x.count)&&x.count>0&&Number.isInteger(x.wave)&&x.wave>=0&&x.wave<=65535)}
function restore(p){if(!valid(p))throw Error('Not a supported quest plan.');plan=p;for(const k of ['name','difficulty','party','brief'])$(k).value=plan[k];render()}
$('import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>2000000)throw Error('Plan is too large.');restore(JSON.parse(await f.text()))}catch(e){alert(e.message)}};
fetch('data/reference.json').then(r=>{if(!r.ok)throw Error('Reference data unavailable');return r.json()}).then(data=>{ref=data;for(const a of ref.floors)option($('area'),a.area,a.name+' · area '+a.area);for(const d of ref.entities)option($(d.kind==='npc'?'npc':'monster'),d.id,(d.qedit_name||d.constructor)+' · '+d.id_hex);$('area').value='1';area();try{const old=localStorage.getItem('psobb-plan-v1');if(old)restore(JSON.parse(old));else render()}catch{render()}}).catch(e=>text($('review'),e.message,'warning'));
