"""Compact AI recipes expanded into explicit, source-derived encounter plans."""
from pathlib import Path
import json,urllib.request,copy,re
ROOT=Path(__file__).resolve().parent
ANCHORS=json.loads((ROOT/'data/forest2-anchors.json').read_text(encoding='utf-8'))
VARIANTS={'savage_wolf':{'type':67,'name':'Savage Wolf','parameter':1,'value':0.0},'barbarous_wolf':{'type':67,'name':'Barbarous Wolf','parameter':1,'value':1.0},'booma':{'type':68,'name':'Booma','parameter':5,'value':0},'gobooma':{'type':68,'name':'Gobooma','parameter':5,'value':1},'gigobooma':{'type':68,'name':'Gigobooma','parameter':5,'value':2}}
SCHEMA={'type':'object','properties':{'name':{'type':'string','maxLength':31},'brief':{'type':'string','maxLength':200},'dialogue':{'type':'string','maxLength':500},'difficulty':{'type':'string','enum':['Normal','Hard','Very Hard','Ultimate']},'party':{'type':'integer','minimum':1,'maximum':4},'waves':{'type':'array','minItems':1,'maxItems':16,'items':{'type':'object','properties':{'enemy':{'type':'string','enum':list(VARIANTS)},'count':{'type':'integer','minimum':1,'maximum':24}},'required':['enemy','count'],'additionalProperties':False}},'unsupported':{'type':'array','items':{'type':'string'}}},'required':['name','brief','dialogue','difficulty','party','waves','unsupported'],'additionalProperties':False}
def expand(recipe):
    if not isinstance(recipe,dict) or not isinstance(recipe.get('waves'),list) or not 1<=len(recipe['waves'])<=16:raise ValueError('Invalid recipe waves')
    if not isinstance(recipe.get('unsupported'),list):raise ValueError('Missing unsupported request report')
    if recipe['unsupported']:raise ValueError('This encounter preset cannot satisfy: '+'; '.join(map(str,recipe['unsupported'])))
    for key,maximum in [('name',31),('brief',200),('dialogue',500)]:
        if not isinstance(recipe.get(key),str) or not 1<=len(recipe[key])<=maximum:raise ValueError('Invalid '+key)
    p=json.loads((ROOT/'examples/research-rescue.json').read_text(encoding='utf-8'));seed=p['waves'][0];p['waves']=[]
    p.update(name=recipe['name'],brief=recipe['brief'],difficulty=recipe['difficulty'],party=recipe['party'])
    p['npcs'][0]['dialogue']=recipe['dialogue']
    for i,w in enumerate(recipe['waves'],1):
        if w.get('enemy') not in VARIANTS:raise ValueError('Unknown enemy variant')
        variant=VARIANTS[w['enemy']];profile=ANCHORS[str(variant['type'])];count=w.get('count')
        if type(count) is not int or not 1<=count<=min(24,len(profile['positions'])):raise ValueError('Count exceeds available anchors or prototype build budget; not a game limit')
        entry=copy.deepcopy(seed);entry.update(type=variant['type'],name=variant['name'],enemyVariant=w['enemy'],wave=i,count=count,positions=copy.deepcopy(profile['positions'][:count]))
        for position in entry['positions']:position['params'][variant['parameter']]=variant['value']
        p['waves'].append(entry)
    p['provenance']['ai']='Recipe generated by Ollama; positions and constructor params expanded from source anchors, not invented by model'
    # Validate domain values, then retain the explicit authored fields.
    from server import validate
    validate(copy.deepcopy(p));return p

def check_preset_request(prompt):
    # Guard common unsupported requests independently of the model. The UI states
    # this preset's scope; this check is not a general natural-language proof.
    text=prompt.lower()
    text=re.sub(r"\b(?:no|without|exclude|excluding)\s+(?:a\s+|any\s+)?(?:boss(?:es)?|rewards?|items?)\b",'',text)
    patterns={'boss encounter':r'\b(?:boss(?:es)?|dragon|de rol le|dark falz|vol opt)\b','another area or episode':r'\b(?:forest\s*1|caves?|mines?|ruins?|episode\s*[24])\b','item or currency rewards':r'\b(?:rewards?|meseta|loot|items?|weapons?)\b'}
    for reason,pattern in patterns.items():
        if re.search(pattern,text):raise ValueError('This Forest 2 preset does not yet support '+reason+'. Use the general planner for an uncompiled design.')

def generate(prompt,model,current=None):
    if not isinstance(prompt,str) or not 1<=len(prompt)<=8000:raise ValueError('Invalid prompt')
    if not isinstance(model,str) or not model or len(model)>100:raise ValueError('Select a local model')
    check_preset_request(prompt)
    menu=[dict(enemy=key,name=v['name'],max_count=min(24,len(ANCHORS[str(v['type'])]['positions']))) for key,v in VARIANTS.items()]
    instruction='You create PSOBB quest recipes. Available preset: Forest 2 room 12, one researcher NPC, an exit door and sequential enemy waves. Select named enemy variants from enemy_menu. Copy each exact enemy key; the builder assigns base IDs and variant parameters. Respect the requested title, party size, difficulty, counts and dialogue. IMPORTANT: unsupported lists ONLY features explicitly requested by the user that this preset cannot implement. If the user requests a rescue story, dialogue, Ultimate, four players and waves from enemy_menu, unsupported MUST be []. Do not list preset restrictions, missing requests, or phrases such as "No boss" in unsupported. A user explicitly asking for another map, a boss, item rewards or more NPCs is unsupported. Bounds of 24 enemies per entry and 16 waves are prototype budgets, not game limits. Return JSON matching the schema, with concise text.'

    context={'request':prompt,'enemy_menu':menu}
    if isinstance(current,dict):context['existing']={k:current.get(k) for k in ('name','brief','difficulty','party')};context['existing']['waves']=[{k:w.get(k) for k in ('enemyVariant','type','count')} for w in current.get('waves',[])]
    payload={'model':model,'stream':False,'think':False,'format':SCHEMA,'options':{'num_ctx':4096,'num_predict':1500,'temperature':0.2},'messages':[{'role':'system','content':instruction},{'role':'user','content':json.dumps(context)}]}
    request=urllib.request.Request('http://127.0.0.1:11434/api/chat',data=json.dumps(payload).encode(),headers={'Content-Type':'application/json'})
    with urllib.request.urlopen(request,timeout=180) as r:result=json.loads(r.read(1000000))
    recipe=json.loads(result['message']['content']);p=expand(recipe);p['aiRecipe']=recipe;return p
